resources:
- ../../base

# generatorOptions:
#   disableNameSuffixHash: true

secretGenerator:
- name: basic-auth
  files:
  - secrets/auth

patchesStrategicMerge:
- ingress-patch.yaml

namePrefix: production-
