resources:
- deployment.yaml
- service.yaml
- ingress.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: config-files
  literals:	
  - foo=bar
  - baz=qux
  files:
    - config/pokus.txt
    - config/pokus1.txt
